// Rewrites the command table in docs/guide/commands.md from the one command registry
// (entry/registry.ts's surfaceRegistry) — the same declarations `--help`, the MCP schemas and
// shell completion read — so the page cannot name a command or an argument the tool does not
// accept. Run via `npm run docs:commands`; docs-commands.check.ts compares the committed block
// with this output byte for byte.

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { monorepoRoot } from "#framework/core/env.ts";
import { checkoutGate, installedGate, surfaceRegistry } from "#framework/entry/registry.ts";
import type { RegistryEntry } from "#framework/integration/gate.ts";
import { GROUP_HEADINGS, GROUP_ORDER, argumentsSignature, destructiveMarker } from "#framework/core/io/help-render.ts";

const BEGIN = "<!-- commands:begin (generated by npm run docs:commands from the command declarations; do not edit) -->";
const END = "<!-- commands:end -->";
const COMMANDS_PAGE = resolve(monorepoRoot, "docs", "guide", "commands.md");
const TABLE_HEAD = "| Command | Arguments | Summary |";
const TABLE_RULE = "| --- | --- | --- |";
const FRAMEWORK_HEADING = "### Framework";
const NO_ARGUMENTS = "—";

/** Which gate offers which gate command, by name: what the table marks as available on one
 *  side only. */
interface GateNames {
  readonly checkout: ReadonlySet<string>;
  readonly installed: ReadonlySet<string>;
}

/** `control-mcp`'s summary names the app the dispatcher was built with; the page covers both
 *  gates and an installed one exposes the deployment's own app, so the name reads as the
 *  placeholder. A summary that no longer matches keeps its app name — visible at the next
 *  rewrite rather than silently substituted. */
const APP_IN_SUMMARY = /^expose (\S+)'s commands as MCP tools/;

function summary(entry: RegistryEntry, gates: GateNames): string {
  // The gate command's own declared effect, marked like a deployment command's row (R18).
  const marker = entry.gate === undefined ? "" : destructiveMarker(entry.gate);
  if (entry.origin === "deployment" && entry.command !== undefined) return `${entry.summary}${destructiveMarker(entry.command)}`;
  if (entry.origin === "gate") {
    if (!gates.installed.has(entry.name)) return `${entry.summary}${marker} (checkout only)`;
    if (!gates.checkout.has(entry.name)) return `${entry.summary}${marker} (installed only)`;
  }
  const app = APP_IN_SUMMARY.exec(entry.summary)?.[1];
  return app === undefined ? `${entry.summary}${marker}` : entry.summary.replace(app, "`<app>`");
}

function row(entry: RegistryEntry, gates: GateNames): string {
  const signature = argumentsSignature(entry.arguments);
  const cell = signature === "" ? NO_ARGUMENTS : `\`${signature.replaceAll("|", "\\|")}\``;
  return `| \`${entry.name}\` | ${cell} | ${summary(entry, gates)} |`;
}

function section(heading: string, entries: readonly RegistryEntry[], gates: GateNames): string {
  return [heading, "", TABLE_HEAD, TABLE_RULE, ...entries.map((entry) => row(entry, gates))].join("\n");
}

/** Every registry entry as one table: a section per command group in print order (the
 *  deployment's own commands in declaration order), then the gate's and the dispatcher's. */
export function renderCommandTables(): string {
  const registry = surfaceRegistry();
  const gates: GateNames = {
    checkout: new Set(checkoutGate().map((command) => command.name)),
    installed: new Set(installedGate("<app-root>").map((command) => command.name)),
  };
  const groups = GROUP_ORDER
    .map((group) => ({ heading: `### ${GROUP_HEADINGS[group]}`, entries: registry.entries.filter((entry) => entry.command?.group === group) }))
    .filter((group) => group.entries.length > 0)
    .map((group) => section(group.heading, group.entries, gates));
  const framework = registry.entries.filter((entry) => entry.origin !== "deployment");
  return [...groups, section(FRAMEWORK_HEADING, framework, gates)].join("\n\n");
}

/** The page with the block between its markers replaced and the rest of it untouched. */
export function spliceGenerated(markdown: string, block: string): string {
  const begin = markdown.indexOf(BEGIN);
  const end = markdown.indexOf(END);
  if (begin === -1 || end === -1 || end < begin) throw new Error(`commands.md needs one ${BEGIN} and one ${END}`);
  return `${markdown.slice(0, begin + BEGIN.length)}\n\n${block}\n\n${markdown.slice(end)}`;
}

// Running this file rewrites the block; importing it only renders.
if (process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const block = renderCommandTables();
  const rows = block.split("\n").filter((line) => line.startsWith("| `")).length;
  await writeFile(COMMANDS_PAGE, spliceGenerated(await readFile(COMMANDS_PAGE, "utf8"), block), "utf8");
  process.stderr.write(`rewrote the command table in docs/guide/commands.md (${rows} rows)\n`);
}
