// docs/guide/commands.md's command table is generated from the one command registry
// (entry/registry.ts's surfaceRegistry) — the declarations `--help`, the MCP schemas and shell
// completion read — so the page cannot name a command or an argument the tool does not accept.
// The block between the markers must equal tools/dev/docs-commands.ts's output byte for byte:
// a hand edit, or a declaration the page never followed, fails here, and the fix is to
// regenerate, never to patch a cell.

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { monorepoRoot } from "#framework/core/env.ts";
import { surfaceRegistry } from "#framework/entry/registry.ts";
import { renderCommandTables } from "#tools/dev/docs-commands.ts";
import { check, finish } from "#checks/kit/harness.ts";

const BEGIN = "<!-- commands:begin (generated by npm run docs:commands from the command declarations; do not edit) -->";
const END = "<!-- commands:end -->";
const REGENERATE = "run npm run docs:commands";
const ROW = /^\| `([a-z][a-z-]*)` \|/;

const page = (await readFile(resolve(monorepoRoot, "docs", "guide", "commands.md"), "utf8")).replaceAll("\r\n", "\n");

check("the page carries exactly one begin marker and one end marker", [page.split(BEGIN).length - 1, page.split(END).length - 1], [1, 1]);

const block = page.slice(page.indexOf(BEGIN) + BEGIN.length, page.indexOf(END)).trim();
check(`the committed block is byte-identical to the generated table (${REGENERATE})`, block, renderCommandTables().trim());

const rows = block.split("\n").filter((line) => ROW.test(line)).map((line) => ROW.exec(line)?.[1] ?? "");
check("every registry entry is one row of the table, and nothing else is", [...rows].sort(), [...surfaceRegistry().names].sort());

finish("docs-commands");