// The registry of negative controls (stage 7, S0.3): for each mechanism a past review round
// fixed, the product edit that would reintroduce it and the check that MUST fail with the
// edit applied. `npm run check:controls` applies each edit to one shared temp copy of the
// repository and demands the failure — a control that no longer fails is a finding, never
// a skip. Invariant I11: an evidence-bearing check ships with a control.

export interface ControlDecl {
  readonly id: string;
  /** The row in docs/internal/review-findings-registry.md whose fix this control pins. */
  readonly finding: string;
  /** One line: which mechanism the control pins. */
  readonly note: string;
  /** Repo-relative, forward slashes. */
  readonly product: string;
  /** Search text that must occur EXACTLY once in the product file. */
  readonly search: string;
  readonly replace: string;
  /** Repo-relative path of the check file that must fail with the edit applied. */
  readonly check: string;
  /** A stable fragment of the failing assertion's name in the check's output. */
  readonly fragment: string;
  /** The check's baseline needs git metadata in the temp copy (e.g. deploy's tracked-files vetting). */
  readonly needsGit?: boolean;
}

export const CONTROLS: readonly ControlDecl[] = [
  {
    id: "C1",
    finding: "R19-06",
    note: "late argument refusal: the binder's parse must own set --name — a kind whose parse accepts everything lets every invalid sample flow past parse to set build's run-stage refusal, failing the sweep's stage assertion",
    product: "tools/framework/commands/sets/set.ts",
    search: `, value: kinds.name("set", "create") }`,
    replace: `, value: { ...kinds.name("set", "create"), parse: (raw: string) => raw } }`,
    check: "tools/checks/foundation/core/command/pipeline/property.check.ts",
    fragment: "refused no later than prepare",
  },
  {
    id: "C2",
    finding: "R18-11",
    note: "destroy --confirm-name value refusal must sit at prepare, not after the context",
    product: "tools/framework/commands/lifecycle/instance/destroy.ts",
    search: "      if (confirmName !== deploymentName()) {\n        throw new ArgumentError(confirmNameMismatch(confirmName), \"confirm-name\");\n      }\n      return { ...values, confirmName };\n    }\n    return { ...values };\n  },\n  async run(ctx, plan) {\n    const targets = destroyTargets(ctx, plan);\n    for (const target of targets) assertSafeRemovalShape(target);\n\n    // Never bootstrapped: no instance or lock home exists \u2014 only the independent dirs can be there.\n    const bootstrapped = await ctx.runtime.isRunning().then(() => true, (error) => {\n      if (error instanceof NotBootstrapped) return false;\n      throw error;\n    });\n\n    if (plan.confirmName === undefined) {",
    replace: "      return { ...values, confirmName };\n    }\n    return { ...values };\n  },\n  async run(ctx, plan) {\n    const targets = destroyTargets(ctx, plan);\n    for (const target of targets) assertSafeRemovalShape(target);\n\n    // Never bootstrapped: no instance or lock home exists \u2014 only the independent dirs can be there.\n    const bootstrapped = await ctx.runtime.isRunning().then(() => true, (error) => {\n      if (error instanceof NotBootstrapped) return false;\n      throw error;\n    });\n\n    if (plan.confirmName !== deploymentName()) {\n      throw new ArgumentError(confirmNameMismatch(plan.confirmName ?? \"\"), \"confirm-name\");\n    }\n    if (plan.confirmName === undefined) {",
    check: "tools/checks/controls/stage-placement.check.ts",
    fragment: "at the prepare stage",
  },
  {
    id: "C3",
    finding: "R18-03",
    note: "advice naming another deployment must keep its own --app, not the current selection's",
    product: "tools/framework/core/io/invocation/render.ts",
    search: `  if (advice.app !== undefined) {
    parts.push("--app", quote(advice.app));
  } else if (`,
    replace: `  if (advice.app !== undefined && false) {
    parts.push("--app", quote(advice.app));
  } else if (`,
    check: "tools/checks/surfaces/advice-matrix.check.ts",
    fragment: "--app names the rule's deployment",
  },
  {
    id: "C4",
    finding: "R18-13",
    note: "toArgv emits positionals from the chosen action's own slice, never the merged declaration",
    product: "tools/framework/integration/mcp/legacy.ts",
    search: `  for (const argument of slice) {
    if (argument.kind !== "positional") continue;`,
    replace: `  for (const argument of declared) {
    if (argument.kind !== "positional") continue;`,
    check: "tools/checks/foundation/core/command/pipeline/property.check.ts",
    fragment: "emits the action's own positionals in its own order",
  },
  {
    id: "C5",
    finding: "R19-01",
    note: "an unreachable target is rethrown by the journal question, never read as no operations",
    product: "tools/framework/service/operations.ts",
    search: "  const files = (await Promise.all([operationsDir(ctx), ...legacyOperationsDirs(ctx)].map(async (directory) => {\n    const listed = await listIfExists(ctx.transport, directory);\n    return listed.kind === \"absent\" ? [] as string[] : listed.value;\n  }))).flat();",
    replace: "  const files = (await Promise.all([operationsDir(ctx), ...legacyOperationsDirs(ctx)].map((directory) =>\n    ctx.transport.listFiles(directory).catch(() => [] as string[]),\n  ))).flat();",
    check: "tools/checks/runtime/transport/target-unreachable.check.ts",
    fragment: "operations reports an unreachable target instead of an empty journal",
  },
  {
    id: "C6",
    finding: "R18-07",
    note: "the --json refusal document's structured `next` advice is masked",
    product: "tools/framework/core/command/execute.ts",
    search: `          next: advice.map(maskedJson),`,
    replace: `          next: advice,`,
    check: "tools/checks/foundation/core/command/pipeline/execute.check.ts",
    fragment: "the --json document carries the refusal's structured remedy",
  },
  {
    id: "C7",
    finding: "R18-23",
    note: "upgrade --dry-run --json carries the pinned image reference",
    product: "tools/framework/commands/lifecycle/instance/upgrade.ts",
    search: `{ ok: true, changed: false, current: previousDigest, channel: target.channel ?? null, target: target.targetDigest, pinnedImage: pinnedReference, upToDate }`,
    replace: `{ ok: true, changed: false, current: previousDigest, channel: target.channel ?? null, target: target.targetDigest, pinnedImage: target.targetDigest, upToDate }`,
    check: "tools/checks/runtime/connection-facts/upgrade/pin-and-digest.check.ts",
    fragment: "JSON dry-run of a tagless tracked-repo digest retains the channel tag",
  },
  {
    id: "C8",
    finding: "R19-18",
    note: "the schema-summary pin in view.check fails when the shared argument table's summary changes",
    product: "tools/framework/commands/interface/groups/shared-arguments.ts",
    search: `  summary: "Take lock",`,
    replace: `  summary: "Take the lock",`,
    check: "tools/checks/foundation/core/command/spec/view.check.ts",
    fragment: "break-lock's schema line is the declared summary",
  },
  {
    id: "C9",
    finding: "R19-15",
    note: "SSH-operator and target-local scheduler ownership derive independently and the check demands equality, so a drift in one path fails it",
    product: "tools/framework/commands/operate/schedule.ts",
    search: `root = await realpath(deploymentDir());`,
    replace: `root = "clawforge-drift";`,
    check: "tools/checks/runtime/schedule/identity.check.ts",
    fragment: "same-basename Windows task names differ",
  },
  {
    id: "C11",
    finding: "R19-18",
    note: "the receipt writer/reader path is compared against the fixture, so a writer or reader that loses identity fails",
    product: "tools/framework/set/artifacts/receipt.ts",
    search: "    await handle.close();\n  }\n  return receipt;",
    replace: "    await handle.close();\n  }\n  return { ...receipt, setName: `${receipt.setName}-drift` };",
    check: "tools/checks/sets/artifact/set-receipt.check.ts",
    fragment: "preserves the receipt",
  },
  {
    id: "C10",
    finding: "R19-15",
    note: "the scheduler's crontab-update refusal keeps the exit code in the operator's text",
    product: "tools/framework/commands/operate/schedule.ts",
    search: "  return `could not update crontab on ${description} (exit ${code}): ${reason}`;",
    replace: "  return `could not update crontab on ${description}: ${reason}`;",
    check: "tools/checks/runtime/schedule/schedule.check.ts",
    fragment: "account lock refusal reaches the operator",
  },
  {
    id: "C12",
    finding: "R19-18",
    note: "the identity probe's evidence names the probe itself (id -u), not just the answer",
    product: "tools/framework/commands/interface/host/contexts.ts",
    search: "  return `the identity probe id -u answered uid ${uid} on ${description}`;",
    replace: "  return `the identity probe answered uid ${uid} on ${description}`;",
    check: "tools/checks/foundation/cli/host.check.ts",
    fragment: "the refusal names where the uid answer came from",
  },
  {
    id: "C13",
    finding: "R18-19",
    note: "the provision-agent recipe mirror copies asset bytes verbatim",
    product: "tools/framework/commands/management/provision-agent/reconcile.ts",
    search: "const content = await readFile(resolve(recipeDir, ...rel.split(\"/\")));",
    replace: "const content = (await readFile(resolve(recipeDir, ...rel.split(\"/\")))).subarray(1);",
    check: "tools/checks/runtime/lifecycle/recipe-portable-content.check.ts",
    fragment: "byte-identical",
    needsGit: true,
  },
  {
    id: "C14",
    finding: "R19-18",
    note: "the deploy framework sync's rsync source is the checkout root itself",
    product: "tools/framework/commands/management/deploy/sync.ts",
    search: "    `${source}/`,\n",
    replace: "    `${source.slice(0, source.lastIndexOf(\"/\"))}/`,\n",
    check: "tools/checks/runtime/service/deploy/checkout-policy/checkout-policy.check.ts",
    fragment: "used the checkout root",
    needsGit: true,
  },
  {
    id: "C15",
    finding: "R19-05",
    note: "a local tar invocation with an unnormalized -C path back inside the owner module",
    product: "tools/framework/set/artifacts/tar.ts",
    search: `return runLocalTar(["-czf", archive, "-C", fromDir, "."], { ...options, archivePath: archive });`,
    replace: `return spawnLocal("tar", ["-czf", archive, "-C", fromDir, "."], { allowFailure: true });`,
    check: "tools/checks/foundation/hygiene/static/local-tar-owner.check.ts",
    fragment: "unnormalized -C in the owner",
  },
  {
    id: "C16",
    finding: "R19-05",
    note: "path normalization removed from the owner's tar arguments",
    product: "tools/framework/set/artifacts/tar.ts",
    search: `const first = await localTarRunner("tar", [...forceLocal, ...args.map(tarLocalPath)], { allowFailure: true, timeoutMs });`,
    replace: `const first = await localTarRunner("tar", [...forceLocal, ...args], { allowFailure: true, timeoutMs });`,
    check: "tools/checks/sets/tar/local-tar-owner.check.ts",
    fragment: "backslash:",
  },
  {
    id: "C17",
    finding: "R19-17",
    note: "an unknown MCP action is refused in the console's words, never silently bound to the default action",
    product: "tools/framework/core/command/parse.ts",
    search: `if (!known.has(word)) dieUnknownAction(word, unknownActionMessage(word, names), names, "action");`,
    replace: `return fallback() ?? dieUnknownAction(word, unknownActionMessage(word, names), names, "action");`,
    check: "tools/checks/foundation/core/command/spec/call.check.ts",
    fragment: "unknown action refuses with the console's words",
  },
  {
    id: "C18",
    finding: "R19-17",
    note: "an Object.prototype member (constructor, toString, __proto__) is never a declared action",
    product: "tools/framework/core/command/parse.ts",
    search: `if (!known.has(word)) dieUnknownAction(word, unknownActionMessage(word, names), names, "action");`,
    replace: `if (false) dieUnknownAction(word, unknownActionMessage(word, names), names, "action");`,
    check: "tools/checks/foundation/core/command/spec/call.check.ts",
    fragment: "prototype name refused with the console's words",
  },
  {
    id: "C20",
    finding: "R19-01 (neighbour)",
    note: "the destination presence check keeps the read contract: a stat the target cannot answer is unknown, not 'no snapshot'",
    product: "tools/framework/service/operations.ts",
    search: "  if (await probeExists(ctx.transport, destination)) return undefined;",
    replace: "  try { if (await ctx.transport.exists(destination)) return undefined; } catch { return undefined; }",
    check: "tools/checks/runtime/transport/scenarios/target-read-sites.check.ts",
    fragment: "a destination the target cannot stat is unknown",
  },
      {
    id: "C21",
    finding: "R19-01 (neighbour)",
    note: "the live-config read keeps the read contract: an unreachable/unreadable source is never read as absent",
    product: "tools/framework/service/operations.ts",
    search: "  const liveRead = await readIfExists(ctx.transport, live);\n  if (liveRead.kind === \"absent\") return undefined;",
    replace: "  let liveRead: { kind: \"absent\" } | { kind: \"present\"; value: string };\n  try { liveRead = (await ctx.transport.exists(live)) ? { kind: \"present\", value: await ctx.transport.readFile(live) } : { kind: \"absent\" }; } catch { liveRead = { kind: \"absent\" }; }\n  if (liveRead.kind === \"absent\") return undefined;",
    check: "tools/checks/runtime/transport/scenarios/target-read-sites.check.ts",
    fragment: "a refused contact is a typed unknown",
  },
  {
    id: "C22",
    finding: "R19-01 (neighbour)",
    note: "the operation-history listing keeps the read contract: an unreadable target is never an empty history",
    product: "tools/framework/service/operations.ts",
    search: "  const files = (await Promise.all([operationsDir(ctx), ...legacyOperationsDirs(ctx)].map(async (directory) => {\n    const listed = await listIfExists(ctx.transport, directory);\n    return listed.kind === \"absent\" ? [] as string[] : listed.value;\n  }))).flat();",
    replace: "  const files = (await Promise.all([operationsDir(ctx), ...legacyOperationsDirs(ctx)].map((directory) =>\n    ctx.transport.listFiles(directory).catch(() => [] as string[]),\n  ))).flat();",
    check: "tools/checks/runtime/transport/scenarios/target-read-sites.check.ts",
    fragment: "an unreadable history directory is unknown",
  },
  {
    id: "C23",
    finding: "R19-07 (neighbour)",
    note: "the read contract always attaches its Advice to an unknown answer",
    product: "tools/framework/runtime/transport/quoting.ts",
    search: "      advice: [command(\"status\", { note: \"reports whether the target answers at all\" })],",
    replace: "      advice: [],",
    check: "tools/checks/runtime/transport/scenarios/target-read-sites.check.ts",
    fragment: "the rendered next step names the project command",
  },
  {
    id: "C40",
    finding: "S2.4",
    note: "apply --expect keeps the hex64 checksum kind, not a dash-permitting grammar-less text kind",
    product: "tools/framework/commands/orchestration/apply.ts",
    search: `, value: kinds.checksum("hex64", { expected: "a declaration checksum", invalid: () => "takes a declaration checksum — 64 hexadecimal digits", example: "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" }) }`,
    replace: `, value: kinds.text("declaration checksum", { leadingDash: "allow" }) }`,
    check: "tools/checks/foundation/core/command/pipeline/property.check.ts",
    fragment: "apply --expect",
  },
  {
    id: "C41",
    finding: "S2.4",
    note: "the hex64 checksum kind pins exactly 64 hexadecimal digits",
    product: "tools/framework/core/values/kinds.ts",
    search: `/^[0-9a-f]{64}$/.test(raw)`,
    replace: `/^[0-9a-f]{4,64}$/.test(raw)`,
    check: "tools/checks/values/kind.check.ts",
    fragment: "checksum hex64 refuses a short prefix",
  },
  {
    id: "C42",
    finding: "S2.4",
    note: "deploy <target> keeps its leading-dash refusal in the sshDestination kind",
    product: "tools/framework/core/values/kinds.ts",
    search: `raw[0] === "-" || /\\s`,
    replace: `raw[0] === "-Z" || /\\s`,
    check: "tools/checks/foundation/core/command/pipeline/property.check.ts",
    fragment: "deploy: <target>",
  },
  {
    id: "C30",
    finding: "S1.2a-D1",
    note: "the program is spelled by the KIND of launch through spell(); deciding by a slash in the handed spelling drops npm's Windows bin wrapper (no slash) to the shim and un-climbs the subdirectory spellings",
    product: "tools/framework/core/io/invocation/render.ts",
    search: `    if (launchRoot !== undefined && launchRoot !== "" && from !== undefined) {`,
    replace: `    if (from !== undefined) { program = handed.includes("/") ? handed : SHIM_PROGRAM; } else if (false) {`,
    check: "tools/checks/surfaces/frame-law.check.ts",
    fragment: "defaultLaunch: local package (win32) | ",
  },
  {
    id: "C31",
    finding: "S1.2a-quoting",
    note: "argument quoting follows the frame's shells (double-quote rule for a frame that pastes into cmd.exe and PowerShell); collapsing both frames onto the POSIX single-quote rule breaks the pasted words in cmd",
    product: "tools/framework/core/io/invocation/render.ts",
    search: `  const quote = (word: string): string => (posixOnly ? posixArgument(word) : shellArgument(word));`,
    replace: `  const quote = (word: string): string => posixArgument(word);`,
    check: "tools/checks/surfaces/frame-law.check.ts",
    fragment: "law: quoting round-trip",
  },
  {
    id: "C60",
    finding: "R19-04",
    note: "createName must keep the Windows reserved-name refusal at creation — a relaxed creator lets `new-app aux` mint an unopenable deployment",
    product: "tools/framework/core/values/names.ts",
    search: "  if (DEVICE_NAMES.has(safe.toLowerCase())) {",
    replace: "  if (false && DEVICE_NAMES.has(safe.toLowerCase())) {",
    check: "tools/checks/values/name-compat.check.ts",
    fragment: "creating \"con\" is refused",
  },
  {
    id: "C61",
    finding: "R19-04",
    note: "readName must stay the historical reader grammar — refusing device names on read strands already-created aux deployments/records",
    product: "tools/framework/core/values/names.ts",
    search: "  if (!PATTERN.test(value)) {\n    throw new Error(invalidNameMessage(kind, value));\n  }\n  return value as NameOf<K>;",
    replace: "  if (!PATTERN.test(value)) {\n    throw new Error(invalidNameMessage(kind, value));\n  }\n  if (DEVICE_NAMES.has(value.toLowerCase())) {\n    throw new Error(reservedNameMessage(kind, value));\n  }\n  return value as NameOf<K>;",
    check: "tools/checks/values/name-compat.check.ts",
    fragment: "a deployment directory named aux is listed",
  },
  {
    id: "C70",
    finding: "S1.2b-O4",
    note: "the relative spelling climbs from the paste directory to the launch root; swapping the rel arguments spells the entry from the root again, where it does not resolve from a subdirectory",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: `  const path = rel(from, root, platform);`,
    replace: `  const path = rel(root, from, platform);`,
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "spells from docs",
  },
  {
    id: "C71",
    finding: "S1.2b-O4",
    note: "npm's bin wrapper keeps its backslash separators for cmd from a subdirectory; forward slashes fail in cmd.exe",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "  return path === \".\" ? WINDOWS_BIN_PROGRAM : `${path.split(\"/\").join(\"\\\\\")}\\\\node_modules\\\\.bin\\\\clawforge`;",
    replace: "  return path === \".\" ? WINDOWS_BIN_PROGRAM : `${path}/node_modules/.bin/clawforge`;",
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "spell npm-bin cmd (from a subdirectory)",
  },
  {
    id: "C72",
    finding: "S1.2b-O4",
    note: "a paste directory outside the launch root spells the entry absolutely (design §2.2); dropping the outside-root test spells a climb out of the root that the named place cannot run",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "    if (!inside) return target;",
    replace: "    if (false) return target;",
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "rel outside the root is absolute",
  },
  {
    id: "C100",
    finding: "S2.7",
    note: "run-stage effect-only changed inference ignores the observed run-entry invariant",
    product: "tools/framework/integration/mcp/call.ts",
    search: `      if (execution.facts.effect === "read") return false;`,
    replace: `      if (execution.facts.effect === "read") return false;\n      if (execution.facts.effect === "destroy") return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "run: changed",
  },
  {
    id: "C101",
    finding: "S2.7",
    note: "environment/context changed inference depends on completed provisioning write, not merely stage",
    product: "tools/framework/integration/mcp/call.ts",
    search: `if (execution.stage === "environment" || execution.stage === "context") return execution.environmentWrote === true;`,
    replace: `if (execution.stage === "environment" || execution.stage === "context") return true;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "context refusal without environment write: literal changed value",
  },
  {
    id: "C102",
    finding: "S2.7",
    note: "a mutating call refused during prepare reports unchanged",
    product: "tools/framework/integration/mcp/call.ts",
    search: `if (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare") return false;`,
    replace: `if (execution.stage === "parse" || execution.stage === "confirm") return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "prepare refusal: literal changed value",
  },
  {
    id: "C103",
    finding: "S2.7",
    note: "changedFact's PRE_RUN_STAGES early return is disabled, so a destroy call refused at confirm/prepare/context falls through to the facts/document rules and reports changed true — the sweep's pre-run literal changed assertions fail",
    product: "tools/framework/integration/mcp/call.ts",
    search: `    if (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare") return false;`,
    replace: `    if (false && (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare")) return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "prepare refusal: literal changed value",
  },
  {
    id: "C50",
    finding: "S2.3",
    note: "an unknown MCP action is refused as such, never silently bound into the default action's slice",
    product: "tools/framework/core/command/parse.ts",
    search: `      if (!known.has(word)) dieUnknownAction(word, unknownActionMessage(word, names), names, "action");\n      return chosen(word, "named", []);`,
    replace: `      if (!known.has(word)) return fallback() ?? dieUnknownAction(word, unknownActionMessage(word, names), names, "action");\n      return chosen(word, "named", []);`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the named call is refused as an unknown action with the console's words",
  },
  {
    id: "C51",
    finding: "S2.3",
    note: "a positional another action owns is refused with the applies-to voice and its <name> label, never read as unknown",
    product: "tools/framework/core/command/parse.ts",
    search: `      if (owners.length > 0) {`,
    replace: `      if (false && owners.length > 0) {`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the applies-to voice keeps the positional label",
  },
  {
    id: "C52",
    finding: "S2.3",
    note: "the MCP surface reports the binder's FIRST refusal in the console's words, never a legacy validate list joined with '; '",
    product: "tools/framework/integration/mcp/server.ts",
    search: `  const confirmed = args.confirm === true;`,
    replace: `  const replayed = validate(command, args, { name });\n  if (replayed.length > 0) {\n    reply(id, { isError: true, content: [{ type: "text", text: maskSecrets(replayed.join("; ")) }] });\n    return;\n  }\n  const confirmed = args.confirm === true;`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the named dispatch reports the first refusal only",
  },
  {
    id: "C80",
    finding: "S3.2",
    note: "declaredConfig must judge the model's declaration — reading desiredStateFile() ambiently again lets a broken carried declaration validate against whatever the selected deployment holds",
    product: "tools/framework/set/ownership/validate.ts",
    search: "function declaredConfig(content: PortableContent, problems: Problem[]): readonly unknown[] {\n  const declared = content.declaration;",
    replace: "const ambientDeclaration = await (async () => {\n  try {\n    return await (await import(\"node:fs/promises\")).readFile((await import(\"#src/runtime/deployment.ts\")).desiredStateFile(), \"utf8\");\n  } catch {\n    return \"[]\";\n  }\n})();\n\nfunction declaredConfig(content: PortableContent, problems: Problem[]): readonly unknown[] {\n  const declared = { ...content.declaration, raw: ambientDeclaration, empty: ambientDeclaration.trim() === \"\", readError: undefined, parseError: undefined, shapeError: undefined, values: undefined };",
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "the declaration is read from the model, not the ambient deployment",
  },
  {
    id: "C81",
    finding: "S3.2",
    note: "the builder must parse every carried file class — skipping recipe.json makes tree and artifact inventories diverge from what the validator judges",
    product: "tools/framework/set/content.ts",
    search: "    if (recipeText !== undefined && !definitionDiagnosed) {",
    replace: "    if (false && recipeText !== undefined && !definitionDiagnosed) {",
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "a recipe.json missing a required field is a finding too",
  },
  {
    id: "C82",
    finding: "S3.2",
    note: "the builder must carry a parse failure for agent/config.json, not swallow it — a dropped diagnostic validates a broken bundle clean",
    product: "tools/framework/set/content.ts",
    search: "    const parsed = await parseAgentDeclaration(agentText, name);",
    replace: `    const parsed = await ((result) => (result.ok ? result : { ok: true as const, value: undefined as unknown as AgentConfig }))(parseAgentDeclaration(agentText, name));`,
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "a malformed agent/config.json is a finding the model carries",
  },
  {
    id: "C83",
    finding: "S3.2",
    note: "checkImagePinned must judge the lock passed in the model's options — re-reading the ambient deployment's lock makes the unpinned-image advice depend on process state",
    product: "tools/framework/set/ownership/validate.ts",
    search: "  const advice = imagePinAdvice(manifest.requires.image, lock);",
    replace: "  const advice = imagePinAdvice(manifest.requires.image, await (await import(\"#src/commands/management/lock.ts\")).readLock());",
    check: "tools/checks/sets/set-validate-image.check.ts",
    fragment: "comes from the explicit lock, not the ambient one",
  },
  {
    id: "C84",
    finding: "S3.2",
    note: "the declaration inventory checksum must cover the original bytes, not the lossy replacement-character UTF-8 round trip",
    product: "tools/framework/set/content.ts",
    search: "checksum: checksumOf(declarationBytes), size: declarationBytes.byteLength",
    replace: "checksum: checksumOf(declarationBytes.toString(\"utf8\")), size: declarationBytes.byteLength",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "declaration checksum preserves original bytes",
  },
  {
    id: "C85",
    finding: "S3.2",
    note: "the declaration refusal must run before recipe enumeration, so an unreadable recipe root cannot mask a malformed declaration",
    product: "tools/framework/set/load.ts",
    search: "    recipes: () => recipeNames(),",
    replace: "    recipes: await recipeNames(),",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "declaration refusal precedes recipe enumeration",
  },
  {
    id: "C90",
    finding: "S1.3 frame reads",
    note: "product invocation reads must stay behind the frame owner and its sanctioned consumers",
    product: "tools/framework/entry/root.ts",
    search: "export async function defaultFrame(appRoot: string, facts: { host: HostPlatform; msys: boolean; cwd: string; checkout?: string }): Promise<Frame> {\n  const launch = await decideLaunch(appRoot, { host: facts.host, checkout: facts.checkout });",
    replace: "export async function defaultFrame(appRoot: string, facts: { host: HostPlatform; msys: boolean; cwd: string; checkout?: string }): Promise<Frame> {\n  const launch = await decideLaunch(appRoot, { host: facts.host, checkout: facts.checkout });\n  invocation();",
    check: "tools/checks/architecture/architecture.check.ts",
    fragment: "frameReads equals the baseline",
  },
  {
    id: "C91",
    finding: "O3 empty OC_APP",
    note: "a blank OC_APP is an explicit empty selection, not the unset default",
    product: "tools/framework/entry/resolve.ts",
    search: "  return value.trim() === \"\" ? { state: \"empty\" } : { state: \"named\", name: value };",
    replace: "  return value.trim() === \"\" ? { state: \"unset\" } : { state: \"named\", name: value };",
    check: "tools/checks/surfaces/frame-law.check.ts",
    fragment: "selection EMPTY OC_APP",
  },
  {
    id: "C92",
    finding: "S1.3 rooted invocation hints",
    note: "production-rendered hints from a rooted frame must name the entry relative to that root and cwd",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "  const path = rel(from, root, platform);",
    replace: "  const path = rel(root, from, platform);",
    check: "tools/checks/integration/apps/invocation-hints-rooted.check.ts",
    fragment: "frame rooted relative hint",
  },
  {
    id: "C93",
    finding: "S1.3 delegated spawn",
    note: "the executed delegated spawn preserves its argv, inherited cwd and selected-app handover",
    product: "tools/framework/entry/delegate.ts",
    search: "    stdio: \"inherit\",\n    env: { ...process.env, [INVOCATION_ENV]: serializeInvocation(handoverOf(frame)), ...(flag ? { [DELEGATED]: \"1\" } : {}) },",
    replace: "    stdio: \"inherit\",\n    cwd: dirname(entry),\n    env: { ...process.env, [INVOCATION_ENV]: serializeInvocation(handoverOf(frame)), ...(flag ? { [DELEGATED]: \"1\" } : {}) },",
    check: "tools/checks/integration/apps/invocation-hints-rooted.check.ts",
    fragment: "delegated spawn inherits cwd",
  },
  {
    id: "C130",
    finding: "S3.2 residual",
    note: "build's refusal selection must use the diagnostic's structural source, not prose — the afterRecipe gate swaps to \"agent-config\", so an agent diagnostic whose text contains \"acceptance.json\" (agentId \"acceptance.json\") wins and the prose-substring bug resurfaces: the expected acceptance refusal is not produced",
    product: "tools/framework/set/load.ts",
    search: "const acceptanceProblem = diagnostics.find((entry) => entry.source === \"acceptance\");",
    replace: "const acceptanceProblem = diagnostics.find((entry) => entry.source === \"agent-config\");",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "refuses with the acceptance error before the agent diagnostic",
  },
  {
    id: "C131",
    finding: "S3.2 residual",
    note: "the portable-content builder's `read` must memoize into `cache` — deleting the memoized entry forces a physical re-read on every access, breaking once-per-path",
    product: "tools/framework/set/content.ts",
    search: "    let pending = cache.get(abs);",
    replace: "    let pending = cache.get(abs);\n    cache.delete(abs);",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "physically read once",
  },

];
