// Negative controls for the stage-7 S4 acceptance fixes: R1-A quoting (per-shell argument
// spelling, the pwsh and bash-fallback rules, cmd's two-parser quoting) and R1-C checkout
// write isolation, and the round-2 fixes (R2-B value kinds, R2-C write isolation, tails V).
// Kept beside stage7.ts so that file stays as it was; controls.ts spreads this list right
// after it.

import type { ControlDecl } from "./controls.ts";

export const STAGE7_ACCEPT_CONTROLS: readonly ControlDecl[] = [
  { id: "C194", finding: "R1-A-1", note: "pwsh apostrophes must double: POSIX '\\'' escaping in a pwsh line is a parse error there",
    product: "tools/framework/core/io/invocation/render.ts", search: `return \`'\${word.replaceAll("'", "''")}'\`;`, replace: "return shellQuote(word);",
    check: "tools/checks/surfaces/advice/real-shells.check.ts", fragment: "R1-A-1: dollar + apostrophe root: the real shell ran the line (pwsh)" },
  { id: "C195", finding: "R1-A-1 D6/O1", note: "the in-bash fallback line must quote by the POSIX rule, not the pwsh rule of the shell the advice names",
    product: "tools/framework/core/io/invocation/render.ts", search: "const posixOnly = inBash || (f.shells.length === 1 && f.shells[0] === \"posix\");", replace: "const posixOnly = f.shells.length === 1 && f.shells[0] === \"posix\";",
    check: "tools/checks/surfaces/advice/real-shells.check.ts", fragment: "R1-A-1: pwsh-named fallback exact argv in bash: the real shell ran the line (bash)" },
  { id: "C196", finding: "R1-A-1 cmd", note: "an embedded quote in a cmd line must be spelled as a doubled quote: a backslash-quote closes cmd's quoting and lets the next & run a second command",
    product: "tools/framework/core/io/invocation/render.ts", search: "`${\"\\\\\".repeat(backslashes * 2)}\"\"`", replace: "`${\"\\\\\".repeat(backslashes)}\\\\\"`",
    check: "tools/checks/surfaces/advice/real-shells.check.ts", fragment: "R1-A-1: quote then ampersand, cmd: intended-argv" },
  {
    id: "C200", finding: "R1-C",
    note: "Restore checkout-anchored ignored scratch; the containment assertion must refuse it before writes.", product: "tools/checks/kit/capabilities/run-guard.check.ts",
    search: "  const claudeDir = resolve(root, \".claude\");",
    replace: "  const claudeDir = resolve(monorepoRoot, \".claude\");",
    check: "tools/checks/kit/capabilities/run-guard.check.ts", fragment: "does not touch checkout",
  },
  {
    id: "C201", finding: "R1-C",
    note: "Restore clean-only alias propagation; the literal reviewer B anchored alias must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  const classify = scopedClassifier(source, masked);",
    replace: "  const clean = cleanIdents(masked);\n  const classify = (expr: string, origin: string) => { const result = classifyTarget(expr, clean, origin); return result === \"UNKNOWN\" ? \"CLEAN\" : result; };",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: reviewer B resolve alias",
  },
  {
    id: "C202", finding: "R1-C",
    note: "Restore size-only observation above 65536 bytes; equal-size apps rewrites must fail.", product: "tools/checks/kit/run.ts",
    search: "hash: await hashFile(absolute)",
    replace: "hash: info.size <= 65536 ? await hashFile(absolute) : undefined",
    check: "tools/checks/kit/capabilities/run-guard.check.ts", fragment: "65537 A to B bytes",
  },
  {
    id: "C203", finding: "R1-C",
    note: "Restore ignored name-only observation; preexisting equal-size content rewrites must fail.", product: "tools/checks/kit/run.ts",
    search: "    ignored: ignoredAvailable ? ignoredEntries : undefined,",
    replace: "    ignored: undefined,",
    check: "tools/checks/kit/capabilities/run-guard.check.ts", fragment: "existing ignored AAAA to BBBB",
  },
  {
    id: "C204", finding: "R1-C",
    note: "Bypass unbound identifier targets; the literal unknown witness must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "    const classification = classify(target, origin, at);",
    replace: "    const classification = classify(target, origin, at);\n    if (classification === \"UNBOUND\") continue;",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: unknown",
  },
  {
    id: "C205", finding: "R1-C",
    note: "Restore the evaluator-only path (no anchored-token floor); the template-literal fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "    const floored = anchoredFloor(classification, target);",
    replace: "    const floored = classification;",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: floor: template literal",
  },
  {
    id: "C210", finding: "R2-C",
    note: "Drop import-based fs binding resolution; the namespace-import fs.promises fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  for (const entry of parseImports(source, masked)) bindImport(b, entry);\n",
    replace: "",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: namespace import fs.promises",
  },
  {
    id: "C211", finding: "R2-C",
    note: "Drop unlink from the destroy-operations table; the unlink fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  unlink: { targets: [0] },\n",
    replace: "",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: unlink",
  },
  {
    id: "C212", finding: "R2-C",
    note: "Drop rm from the destroy-operations table; the rmSync fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  rm: { targets: [0] },\n",
    replace: "",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: rmSync",
  },
  {
    id: "C213", finding: "R2-C",
    note: "Drop the child-process rule; the git clean fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  hits.push(...childProcessHits(source, masked, classify, children));\n",
    replace: "",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: git clean",
  },
  {
    id: "C214", finding: "R2-C",
    note: "Classify only a move's destination; the anchored rename source fixture must fail.", product: "tools/checks/foundation/hygiene/static/write-isolation-rules.ts",
    search: "  rename: { targets: [0, 1] },",
    replace: "  rename: { targets: [1] },",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "write-isolation literal: rename source anchored",
  },
  {
    id: "C206", finding: "rf7-tails-V",
    note: "Restore the dist exclusion; the dist self-check must fail.", product: "tools/checks/kit/run.ts",
    search: "const IGNORED_STATUS_EXCLUDES = [\"node_modules\", \"apps\", \"worktrees\", \".rush\"];",
    replace: "const IGNORED_STATUS_EXCLUDES = [\"node_modules\", \"apps\", \"worktrees\", \"tools/framework/dist\", \".rush\"];",
    check: "tools/checks/kit/capabilities/run-guard.check.ts", fragment: "a new file under tools/framework/dist is reported",
  },
  {
    id: "C207", finding: "rf7-tails-V",
    note: "One more unresolved (parameter-bound) write target in a scanned check; the writeTargetsUnresolved ratchet must fail.", product: "tools/checks/foundation/core/command/needs.check.ts",
    search: "finish(\"needs\");",
    replace: "finish(\"needs\");\nexport function controlC207(target: string): Promise<void> { return writeFile(target, \"x\"); } // control C207: one more unresolved write target",
    check: "tools/checks/foundation/hygiene/static/write-isolation.check.ts", fragment: "unresolved write targets only shrink",
  },
  {
    id: "C208", finding: "rf7-tails-V",
    note: "Bypass the counted reader in inspect's declared state; the dynamic count assertion must fail.", product: "tools/framework/commands/orchestration/inspect/declared.ts",
    search: "suspiciousEnvLines(await readEnvFileText())",
    replace: "suspiciousEnvLines(await readFile(envFile(), \"utf8\"))",
    check: "tools/checks/foundation/core/command/needs.check.ts", fragment: "reads the .env through the counted reader exactly once",
  },
  {
    id: "C209", finding: "rf7-tails-V",
    note: "Bypass the counted reader in the secrets apply path; the static sweep must fail.", product: "tools/framework/commands/management/secrets.ts",
    search: "let content = await readEnvFileText();",
    replace: "let content = await readFile(envFile(), \"utf8\");",
    check: "tools/checks/foundation/core/command/needs.check.ts", fragment: "no product file reads envFile() past the counted reader",
  },
  {
    id: "C225", finding: "R2-B-1",
    note: "Drop text's control-character refusal; the sweep's NUL case for verify <archive> must stop past parse.", product: "tools/framework/core/values/kinds.ts",
    search: "  }, invalid, { controls: refused });",
    replace: "  }, invalid, { controls: /(?!)/ });",
    check: "tools/checks/foundation/core/command/pipeline/property/property-control-chars.check.ts", fragment: "verify: <archive> \"a\\u0000b\": MCP stops at the parse stage",
  },
  {
    id: "C226", finding: "R2-B-4",
    note: "Restore the function-valued description; the backup install scheduler control must stop short of the transport sentinel.", product: "tools/checks/kit/deployment-fixture.ts",
    search: "    { description: FIXTURE_TRANSPORT_DESCRIPTION },",
    replace: "    {},",
    check: "tools/checks/foundation/core/command/pipeline/property/property.check.ts", fragment: "backup install: control reaches the transport sentinel",
  },
  {
    id: "C227", finding: "R2-B-1",
    note: "Bypass the uniform kind wrapper; bootstrap --break-foreign-lock with a NUL must stop past parse.", product: "tools/framework/core/values/kinds.ts",
    search: "controls.test(raw)) throw",
    replace: "controls.test(\"\")) throw",
    check: "tools/checks/foundation/core/command/pipeline/property/property-control-chars.check.ts", fragment: "bootstrap: --break-foreign-lock \"a\\u0000b\": MCP stops at the parse stage",
  },
  {
    id: "C228", finding: "R2-B-1",
    note: "Let multi-line text accept every control character; exec <args…> with a NUL must stop past parse.", product: "tools/framework/core/values/kinds.ts",
    search: "options.lines === \"multi\" ? CONTROL_BUT_LINES : CONTROL;",
    replace: "options.lines === \"multi\" ? /(?!)/ : CONTROL;",
    check: "tools/checks/foundation/core/command/pipeline/property/property-control-chars.check.ts", fragment: "exec: <args…> \"a\\u0000b\": MCP stops at the parse stage",
  },
  {
    id: "C229", finding: "R2-B-1",
    note: "Print the raw value in the control-character refusal; the refusal must never carry a raw control character.", product: "tools/framework/core/values/kinds.ts",
    search: "not \"${shown(raw)}\"",
    replace: "not \"${raw}\"",
    check: "tools/checks/foundation/core/command/pipeline/property/property-control-chars.check.ts", fragment: "the message carries no raw control character",
  },
  {
    id: "C220", finding: "R2-C-3",
    note: "Disable the runner checkout verdict.", product: "tools/checks/kit/run.ts",
    search: "  if (changed.length > 0) {", replace: "  if (false) {",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "runner diff enforces failure",
  },
  {
    id: "C221", finding: "R2-C-3",
    note: "Disable capability probing.", product: "tools/checks/kit/run.ts",
    search: "  const missing = await probe.missing(entry.requires);", replace: "  const missing: Capability[] = [];",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "absent capability is skipped without spawning writer",
  },
  {
    id: "C222", finding: "R2-C-2 R2-B-3",
    note: "Restore status-only tracked and untracked observation.", product: "tools/checks/kit/run.ts",
    search: "  if (before.tree !== undefined && after.tree !== undefined) changes.push(...diffEntries(before.tree, after.tree, \"checkout content\"));", replace: "",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "dirty tracked rewrite is content-bearing",
  },
  {
    id: "C223", finding: "R2-C-6",
    note: "Throw on locked files again.", product: "tools/checks/kit/run.ts",
    search: "    if (code === \"EBUSY\" || code === \"EPERM\" || code === \"EACCES\") {", replace: "    if (false) {",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "unreadable sentinel does not throw EBUSY",
  },
  {
    id: "C224", finding: "R2-C-5",
    note: "Drop mode observation.", product: "tools/checks/kit/run.ts",
    search: "    mode = info.mode;", replace: "    mode = undefined;",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "mode guard observes chmod",
  },
  {
    id: "C217", finding: "R2-C",
    note: "Reallow dollar-variable repository text; the reviewer repo$HOME refusal must fail.", product: "tools/framework/runtime/docker/image-ref.ts",
    search: "  if (!REPOSITORY.test(repository)) return undefined;",
    replace: "  if (!REPOSITORY.test(repository.replace(/\\$[A-Za-z_][A-Za-z0-9_]*/g, \"x\"))) return undefined;",
    check: "tools/checks/runtime/connection-facts/upgrade/image-ref.check.ts", fragment: "reviewer repository refused: repo$HOME",
  },
  {
    id: "C215", finding: "R2-C",
    note: "Disable measureProseHeldFlow constant carrying; its new const-held check fixture must fail independently of the legacy scanner.", product: "tools/checks/architecture/prose-held.ts",
    search: "  const carrying = (name: string, call: boolean, at: number, from: Scope, seen = new Set<Binding>(), path: string[] = []): boolean => {",
    replace: "  const carrying = (name: string, call: boolean, at: number, from: Scope, seen = new Set<Binding>(), path: string[] = []): boolean => { return false;",
    check: "tools/checks/architecture/self/prose-held.check.ts", fragment: "flow: reviewer const-held check",
  },
  {
    id: "C216", finding: "R2-C",
    note: "Disable measureProseHeldFlow node:assert recognition; its new assert.equal fixture must fail independently of the legacy scanner.", product: "tools/checks/architecture/prose-held.ts",
    search: "  const { receivers, bare } = assertNames(source);",
    replace: "  const receivers = new Set<string>(); const bare = new Map<string, string>();",
    check: "tools/checks/architecture/self/prose-held.check.ts", fragment: "flow: reviewer assert.equal",
  },
  {
    id: "C240", finding: "rf7-tails-u", note: "Restore inherited runner requirements; isolated capture must skip an optional missing capability.",
    product: "tools/checks/kit/self/runtime-guard.check.ts", search: "  for (const [key] of inherited) delete process.env[key];", replace: "  // control: inherit outer requirements",
    check: "tools/checks/kit/self/runtime-guard.check.ts", fragment: "absent capability is skipped without spawning writer",
  },
  {
    id: "C241", finding: "rf7-tails-u", note: "Treat ordinary-string interpolation spelling as computed; literal prose assertion must fail.",
    product: "tools/checks/architecture/prose-held.ts", search: 'if (!template || text[i] !== "$" || text[i + 1] !== "{")', replace: 'if (text[i] !== "$" || text[i + 1] !== "{")',
    check: "tools/checks/architecture/self/prose-held.check.ts", fragment: "ordinary single-quoted interpolation spelling is literal prose",
  },
  {
    id: "C242", finding: "rf7-tails-u", note: "Restore target-context status advice; recovery diagnostic kind and argv must fail.",
    product: "tools/framework/commands/operate/recover-env/bootstrap.ts", search: 'override readonly advice = [command(["recover-env", "--dry-run"])];', replace: 'override readonly advice = [command("status")];',
    check: "tools/checks/kit/self/recovery-advice.check.ts", fragment: "every local recovery unknown carries diagnostic kind and argv",
  },
  {
    id: "C244", finding: "rf7-tails-u", note: "Bypass secrets apply counted reader; dynamic calibration must fail independently of static sweep.",
    product: "tools/framework/commands/management/secrets.ts", search: "let content = await readEnvFileText();", replace: 'let content = await readFile(envFile(), "utf8");',
    check: "tools/checks/foundation/core/command/needs.check.ts", fragment: "secrets apply reads the .env through the counted reader exactly once",
  },
  {
    id: "C230", finding: "R1-A-2",
    note: "Restore the previous-call cwd selection guard; fresh advice after a flag-selected aux must still bypass demo.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "    && resolvesByCwd(frame.launch, on.program);",
    replace: "    && frame.app.state === \"selected\" && frame.app.by === \"cwd\"\n    && resolvesByCwd(frame.launch, on.program);",
    check: "tools/checks/surfaces/advice/advice-anchor.check.ts",
    fragment: "R1-A-2 cmd: fresh explicit/inherited aux advice uses O2, not --app",
  },
  {
    id: "C231", finding: "R1-A-1 native pwsh",
    note: "Drop legacy native handoff protection; the real npm .ps1 wrapper must receive exact argv.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: `if (only === "pwsh" && needsLegacy(word))`,
    replace: `if (false && needsLegacy(word))`,
    check: "tools/checks/surfaces/advice/real-shells.check.ts",
    fragment: "native powershell.exe .ps1: exact argv",
  },
  {
    id: "C232", finding: "R1-A-2 inherited selector",
    note: "Ignore inherited flag/env/sole app when detecting a fresh-paste conflict; inherited aux advice must use O2 too.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: `  const targetApp = advice.app ?? (!isGateCommand(advice.argv[0]) && options?.deploymentFree !== true\n    && frame.app.state === "selected" && ["flag", "env", "sole"].includes(frame.app.by)\n    ? frame.app.name : undefined);`,
    replace: "  const targetApp = advice.app;",
    check: "tools/checks/surfaces/advice/advice-anchor.check.ts",
    fragment: "R1-A-2 cmd: fresh explicit/inherited aux advice uses O2, not --app",
  },
  {
    id: "C233", finding: "R1-A-1 native trailing backslash",
    note: "Keep quote protection but drop spaced trailing-backslash protection for legacy native pwsh handoff.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: ` && word.endsWith("\\\\"))`,
    replace: ` && false)`,
    check: "tools/checks/surfaces/advice/real-shells.check.ts",
    fragment: "native powershell.exe .ps1: exact argv",
  },
  {
    id: "C234", finding: "R1-A-1 native backslash before quote",
    note: "Keep doubled embedded quotes but stop doubling preceding backslashes; native handoff loses the literal backslash before quote.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "`${\"\\\\\".repeat(backslashes * 2)}\"\"`",
    replace: "`${\"\\\\\".repeat(backslashes)}\"\"`",
    check: "tools/checks/surfaces/advice/real-shells.check.ts",
    fragment: "native powershell.exe .ps1: exact argv",
  },
  {
    id: "C235", finding: "R1-A-3 scoped preference",
    note: "Drop scoped Legacy preference; the static row assertion must fail without PS7.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "$PSNativeCommandArgumentPassing = 'Legacy'; ${text}",
    replace: "${text}",
    check: "tools/checks/surfaces/advice/real-shells.check.ts",
    fragment: "native advice: scoped Legacy block present",
  },
  {
    id: "C236", finding: "R1-A-2 external cwd",
    note: "Erase the frame by-cwd value outside apps; external deployment advice must retain O2.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: '    if (!isAbsolute(underApps) && segments[0] !== ".." && segments[0] !== "") cwdApp = segments[0];',
    replace: '    cwdApp = !isAbsolute(underApps) && segments[0] !== ".." && segments[0] !== "" ? segments[0] : undefined;',
    check: "tools/checks/surfaces/advice/advice-anchor.check.ts",
    fragment: "R1-A-2 external cwd retains frame by-cwd selection",
  },
  {
    id: "C270", finding: "R3-B-1",
    note: "Restore flat merged tokenization; invalid recipe new Advice must emit no machine step.",
    product: "tools/framework/integration/mcp/call.ts",
    search: "    return commandBinding.inverseCall(shape, argv.slice(1), argv[0]);",
    replace: `    const declared = command.arguments ?? [];
    const verbatim = declared.some((argument) => argument.kind === "variadic" && "verbatim" in argument && argument.verbatim === true);
    const entries = commandBinding.tokenize(declared, argv.slice(1), undefined, verbatim).entries;
    const result: Record<string, unknown> = {};
    for (const { argument, value } of entries) {
      if (argument.kind === "variadic") {
        const list = result[argument.name];
        if (Array.isArray(list)) list.push(value);
        else result[argument.name] = [value];
      } else result[argument.name] = value;
    }
    return result;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-envelope.check.ts",
    fragment: "R3-B-1 recipe new r3-name r3-extra: no machine step",
  },
  {
    id: "C271", finding: "R3-B-1 raw projection",
    note: "Restore legacy and variadic conversion in the outgoing raw projection.",
    product: "tools/framework/core/command/parse/index.ts",
    search: "...raw };",
    replace: "...toParsedArgs(tokens.entries) };",
    check: "tools/checks/integration/mcp/dispatch/mcp-envelope.check.ts",
    fragment: "R3-B-1 legacy numeric: exact raw named arguments",
  },
  {
    id: "C250", finding: "R3-A-1", note: "Restore the unavailable installed-command override for a checkout conflict.",
    product: "tools/framework/core/io/invocation/render.ts",
    search: '  // Arguments quote by the frame\'s shells, not by the program\'s spelling: a frame that',
    replace: '  if (cwdConflict) program = "clawforge";\n  // Arguments quote by the frame\'s shells, not by the program\'s spelling: a frame that',
    check: "tools/checks/surfaces/advice/checkout-paste.check.ts", fragment: "R3-A-1: checkout-only rendered paste exit 0",
  },
  {
    id: "C251", finding: "R3-A-2 probe transport", note: "Restore native bash -c script transport: repeated tails already drift before Node runs.",
    product: "tools/checks/surfaces/advice/checkout-paste.check.ts",
    search: 'await runProcess("bash", ["-s"], { input: body, timeoutMs })',
    replace: 'await runProcess("bash", ["-c", body], { timeoutMs })',
    check: "tools/checks/surfaces/advice/checkout-paste.check.ts", fragment: "R3-A-2: pre-native exact argv",
  },
];
