// Negative controls of stage 7 steps S1.2b onward (S3.1, S1.2b, S2.7, S2.5, S2.3, S3.2, S1.3, S1.4,
// review tails); the registry and its contract live in ./controls.ts.

import type { ControlDecl } from "./controls.ts";

export const STAGE7_CONTROLS: readonly ControlDecl[] = [
  {
    id: "C60",
    finding: "R19-04",
    note: "createName must keep the Windows reserved-name refusal at creation — a relaxed creator lets `new-app aux` mint an unopenable deployment",
    product: "tools/framework/core/values/names.ts",
    search: "  if (DEVICE_NAMES.has(safe.toLowerCase())) {",
    replace: "  if (false && DEVICE_NAMES.has(safe.toLowerCase())) {",
    check: "tools/checks/values/name-compat.check.ts",
    fragment: "creating \"con\" is refused",
  },
  {
    id: "C61",
    finding: "R19-04",
    note: "readName must stay the historical reader grammar — refusing device names on read strands already-created aux deployments/records",
    product: "tools/framework/core/values/names.ts",
    search: "  if (!PATTERN.test(value)) {\n    throw new Error(invalidNameMessage(kind, value));\n  }\n  return value as NameOf<K>;",
    replace: "  if (!PATTERN.test(value)) {\n    throw new Error(invalidNameMessage(kind, value));\n  }\n  if (DEVICE_NAMES.has(value.toLowerCase())) {\n    throw new Error(reservedNameMessage(kind, value));\n  }\n  return value as NameOf<K>;",
    check: "tools/checks/values/name-compat.check.ts",
    fragment: "a deployment directory named aux is listed",
  },
  {
    id: "C70",
    finding: "S1.2b-O4",
    note: "the relative spelling climbs from the paste directory to the launch root; swapping the rel arguments spells the entry from the root again, where it does not resolve from a subdirectory",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: `  const path = rel(from, root, platform);`,
    replace: `  const path = rel(root, from, platform);`,
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "spells from docs",
  },
  {
    id: "C71",
    finding: "S1.2b-O4",
    note: "npm's bin wrapper keeps its backslash separators for cmd from a subdirectory; forward slashes fail in cmd.exe",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "  return path === \".\" ? WINDOWS_BIN_PROGRAM : `${path.split(\"/\").join(\"\\\\\")}\\\\node_modules\\\\.bin\\\\clawforge`;",
    replace: "  return path === \".\" ? WINDOWS_BIN_PROGRAM : `${path}/node_modules/.bin/clawforge`;",
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "spell npm-bin cmd (from a subdirectory)",
  },
  {
    id: "C72",
    finding: "S1.2b-O4",
    note: "a paste directory outside the launch root spells the entry absolutely (design §2.2); dropping the outside-root test spells a climb out of the root that the named place cannot run",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "    if (!inside) return target;",
    replace: "    if (false) return target;",
    check: "tools/checks/foundation/invocation/frame.check.ts",
    fragment: "rel outside the root is absolute",
  },
  {
    id: "C100",
    finding: "S2.7",
    note: "run-stage effect-only changed inference ignores the observed run-entry invariant",
    product: "tools/framework/integration/mcp/call.ts",
    search: `      if (execution.facts.effect === "read") return false;`,
    replace: `      if (execution.facts.effect === "read") return false;\n      if (execution.facts.effect === "destroy") return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "run: changed",
  },
  {
    id: "C101",
    finding: "S2.7",
    note: "environment/context changed inference depends on completed provisioning write, not merely stage",
    product: "tools/framework/integration/mcp/call.ts",
    search: `if (execution.stage === "environment" || execution.stage === "context") return execution.environmentWrote === true;`,
    replace: `if (execution.stage === "environment" || execution.stage === "context") return true;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "context refusal without environment write: literal changed value",
  },
  {
    id: "C102",
    finding: "S2.7",
    note: "a mutating call refused during prepare reports unchanged",
    product: "tools/framework/integration/mcp/call.ts",
    search: `if (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare") return false;`,
    replace: `if (execution.stage === "parse" || execution.stage === "confirm") return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "prepare refusal: literal changed value",
  },
  {
    id: "C103",
    finding: "S2.7",
    note: "changedFact's PRE_RUN_STAGES early return is disabled, so a destroy call refused at confirm/prepare/context falls through to the facts/document rules and reports changed true — the sweep's pre-run literal changed assertions fail",
    product: "tools/framework/integration/mcp/call.ts",
    search: `    if (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare") return false;`,
    replace: `    if (false && (execution.stage === "parse" || execution.stage === "confirm" || execution.stage === "prepare")) return false;`,
    check: "tools/checks/integration/mcp/dispatch/mcp-changed.check.ts",
    fragment: "prepare refusal: literal changed value",
  },
  {
    id: "C110",
    finding: "S2.5",
    note: "NC-S2-accept-order: acceptFromSource's Q5 pre-pass of loadChecks is moved back after observeRuntime/gatherInspection, so a content refusal over the --set artifact costs a trip to the target — the Q5 guard's ZERO-contacts assertion fails",
    product: "tools/framework/commands/orchestration/accept.ts",
    search: `  const checksByRecipe = new Map<string, AcceptanceCheck[]>();
  for (const recipe of recipes) {
    const checks = await loadChecks(recipe);
    if (checks === undefined) die(\`recipe "\${recipe}" declares no acceptance checks (recipes/\${recipe}/acceptance.json)\`);
    checksByRecipe.set(recipe, checks);
  }

  const before = verified === undefined ? undefined : await observeRuntime(ctx, verified.manifest);
  let matchedBefore = false;
  if (verified !== undefined) {
    try { matchedBefore = isHealthy(await gatherInspection(ctx)); } catch { /* Unverified binding. */ }
  }`,
    replace: `  const before = verified === undefined ? undefined : await observeRuntime(ctx, verified.manifest);
  let matchedBefore = false;
  if (verified !== undefined) {
    try { matchedBefore = isHealthy(await gatherInspection(ctx)); } catch { /* Unverified binding. */ }
  }

  const checksByRecipe = new Map<string, AcceptanceCheck[]>();
  for (const recipe of recipes) {
    const checks = await loadChecks(recipe);
    if (checks === undefined) die(\`recipe "\${recipe}" declares no acceptance checks (recipes/\${recipe}/acceptance.json)\`);
    checksByRecipe.set(recipe, checks);
  }`,
    check: "tools/checks/security/acceptance/accept.check.ts",
    fragment: "ZERO target contacts (the Q5 guard)",
  },
  {
    id: "C111",
    finding: "S2.5",
    note: "kinds.recipeRef's prepare-stage resolve (missing-recipe refusal with zero contacts) is deleted, so a missing recipe reaches the guarded run — recipe-prepare's prepare-stage pin fails",
    product: "tools/framework/core/values/kinds.ts",
    search: `  ], {
    resolve: async (value, local) => {
      const { recipesDirectory } = await import("#src/service/recipe.ts");
      if (!(await local.exists(resolvePath(recipesDirectory(), value, "recipe.json")))) throw new UserError(missingRecipeRefusal(value));
      return recipeRefOf(value);
    },
  });`,
    replace: `  ], {});`,
    check: "tools/checks/integration/recipe/recipe-prepare.check.ts",
    fragment: "stops at the prepare stage",
  },
  {
    id: "C112",
    finding: "S2.5",
    note: "set try's missing-artifact refusal is lifted out of prepare's derive (the plan carries an unverified path), so the .env/secrets reads in run happen before the artifact fact fires — set-command's prepare-stage pin fails",
    product: "tools/framework/commands/sets/set-try.ts",
    search: `const SET_ARTIFACT = kinds.localFile("a set artifact path");`,
    replace: `const SET_ARTIFACT = { ...kinds.localFile("a set artifact path"), resolve: undefined }; // control C112: the prepare-stage existence proof is skipped`,
    check: "tools/checks/sets/set-command.check.ts",
    fragment: "stops at the prepare stage",
  },
  {
    id: "C113",
    finding: "S2.5",
    note: "NC-S2-grammar-in-run: recipe status's run re-validates the name through the readName grammar mint inside the run body — the static grammar-in-run architecture check (zero tolerance in run bodies) fails",
    product: "tools/framework/commands/management/recipe/index.ts",
    search: `      run: (ctx, values) => runStatusAction(ctx, values.name),`,
    replace: `      run: (ctx, values) => { const name = readName("recipe", values.name); return runStatusAction(ctx, name); },`,
    check: "tools/checks/architecture/command-layer/grammar-in-run.check.ts",
    fragment: "grammar call in a run body",
  },
  {
    id: "C115",
    finding: "S2.5",
    note: "NC-S2-grammar-in-run: a grammar mint injected into a run-installed helper (set build's `run: buildAction` indirection — an expression-arrow or identifier form the scan previously could not see) must fail the static grammar-in-run architecture check",
    product: "tools/framework/commands/sets/set.ts",
    search: `async function buildAction(ctx: Context, plan: BuildPlan): Promise<void> {
  const built = await buildSet(ctx, plan.name);`,
    replace: `async function buildAction(ctx: Context, plan: BuildPlan): Promise<void> {
  const injected = readName("recipe", plan.name); // control C115: a grammar mint inside a run-installed helper
  const built = await buildSet(ctx, injected);`,
    check: "tools/checks/architecture/command-layer/grammar-in-run.check.ts",
    fragment: "grammar call in a run body",
  },
  {
    id: "C114",
    finding: "S2.5",
    note: "preparedPlan forwards the raw call.values instead of the resolved map — prepare and the identity plan see the parser's strings, not the kinds' resolved R",
    product: "tools/framework/core/command/spec.ts",
    search: `  return prepared(phases.prepare === undefined ? resolved : await phases.prepare(prepareCallOf(settled, byName, local), local));`,
    replace: `  return prepared(phases.prepare === undefined ? call.values : await phases.prepare(prepareCallOf(call, byName, local), local)); // control C114: the raw call.values is forwarded, the resolved map dropped`,
    check: "tools/checks/foundation/core/command/pipeline/resolve/prepare-resolve.check.ts",
    fragment: "carries the resolved",
  },
  {
    id: "C50",
    finding: "S2.3",
    note: "an unknown MCP action is refused as such, never silently bound into the default action's slice",
    product: "tools/framework/core/command/parse/index.ts",
    search: `      if (!known.has(word)) dieUnknownAction(word, unknownActionMessage(word, names), names, "action");\n      return chosen(word, "named", []);`,
    replace: `      if (!known.has(word)) return fallback() ?? dieUnknownAction(word, unknownActionMessage(word, names), names, "action");\n      return chosen(word, "named", []);`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the named call is refused as an unknown action with the console's words",
  },
  {
    id: "C51",
    finding: "S2.3",
    note: "a positional another action owns is refused with the applies-to voice and its <name> label, never read as unknown",
    product: "tools/framework/core/command/parse/index.ts",
    search: `      if (owners.length > 0) {`,
    replace: `      if (false && owners.length > 0) {`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the applies-to voice keeps the positional label",
  },
  {
    id: "C52",
    finding: "S2.3",
    note: "the MCP surface reports the binder's FIRST refusal in the console's words, never a legacy validate list joined with '; '",
    product: "tools/framework/integration/mcp/server.ts",
    search: `  const confirmed = args.confirm === true;`,
    replace: `  const replayed = validate(command, args, { name });\n  if (replayed.length > 0) {\n    reply(id, { isError: true, content: [{ type: "text", text: maskSecrets(replayed.join("; ")) }] });\n    return;\n  }\n  const confirmed = args.confirm === true;`,
    check: "tools/checks/foundation/core/command/spec/binder.check.ts",
    fragment: "the named dispatch reports the first refusal only",
  },
  {
    id: "C80",
    finding: "S3.2",
    note: "declaredConfig must judge the model's declaration — reading desiredStateFile() ambiently again lets a broken carried declaration validate against whatever the selected deployment holds",
    product: "tools/framework/set/ownership/validate.ts",
    search: "function declaredConfig(content: PortableContent, problems: Problem[]): readonly unknown[] {\n  const declared = content.declaration;",
    replace: "const ambientDeclaration = await (async () => {\n  try {\n    return await (await import(\"node:fs/promises\")).readFile((await import(\"#src/runtime/deployment.ts\")).desiredStateFile(), \"utf8\");\n  } catch {\n    return \"[]\";\n  }\n})();\n\nfunction declaredConfig(content: PortableContent, problems: Problem[]): readonly unknown[] {\n  const declared = { ...content.declaration, raw: ambientDeclaration, empty: ambientDeclaration.trim() === \"\", readError: undefined, parseError: undefined, shapeError: undefined, values: undefined };",
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "the declaration is read from the model, not the ambient deployment",
  },
  {
    id: "C81",
    finding: "S3.2",
    note: "the builder must parse every carried file class — skipping recipe.json makes tree and artifact inventories diverge from what the validator judges",
    product: "tools/framework/set/content.ts",
    search: "    if (recipeText !== undefined && !definitionDiagnosed) {",
    replace: "    if (false && recipeText !== undefined && !definitionDiagnosed) {",
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "a recipe.json missing a required field is a finding too",
  },
  {
    id: "C82",
    finding: "S3.2",
    note: "the builder must carry a parse failure for agent/config.json, not swallow it — a dropped diagnostic validates a broken bundle clean",
    product: "tools/framework/set/content.ts",
    search: "    const parsed = await parseAgentDeclaration(agentText, name);",
    replace: `    const parsed = await ((result) => (result.ok ? result : { ok: true as const, value: undefined as unknown as AgentConfig }))(parseAgentDeclaration(agentText, name));`,
    check: "tools/checks/sets/lifecycle/set-validate.check.ts",
    fragment: "a malformed agent/config.json is a finding the model carries",
  },
  {
    id: "C83",
    finding: "S3.2",
    note: "checkImagePinned must judge the lock passed in the model's options — re-reading the ambient deployment's lock makes the unpinned-image advice depend on process state",
    product: "tools/framework/set/ownership/validate.ts",
    search: "  const advice = imagePinAdvice(manifest.requires.image, lock);",
    replace: "  const advice = imagePinAdvice(manifest.requires.image, await (await import(\"#src/commands/management/lock.ts\")).readLock());",
    check: "tools/checks/sets/set-validate-image.check.ts",
    fragment: "comes from the explicit lock, not the ambient one",
  },
  {
    id: "C84",
    finding: "S3.2",
    note: "the declaration inventory checksum must cover the original bytes, not the lossy replacement-character UTF-8 round trip",
    product: "tools/framework/set/content.ts",
    search: "checksum: checksumOf(declarationBytes), size: declarationBytes.byteLength",
    replace: "checksum: checksumOf(declarationBytes.toString(\"utf8\")), size: declarationBytes.byteLength",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "declaration checksum preserves original bytes",
  },
  {
    id: "C85",
    finding: "S3.2",
    note: "the declaration refusal must run before recipe enumeration, so an unreadable recipe root cannot mask a malformed declaration",
    product: "tools/framework/set/load.ts",
    search: "    recipes: () => recipeNames(),",
    replace: "    recipes: await recipeNames(),",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "declaration refusal precedes recipe enumeration",
  },
  {
    id: "C90",
    finding: "S1.3 frame reads",
    note: "product invocation reads must stay behind the frame owner and its sanctioned consumers",
    product: "tools/framework/entry/root.ts",
    search: "export async function defaultFrame(appRoot: string, facts: { host: HostPlatform; msys: boolean; cwd: string; checkout?: string }): Promise<Frame> {\n  const launch = await decideLaunch(appRoot, { host: facts.host, checkout: facts.checkout });",
    replace: "export async function defaultFrame(appRoot: string, facts: { host: HostPlatform; msys: boolean; cwd: string; checkout?: string }): Promise<Frame> {\n  const launch = await decideLaunch(appRoot, { host: facts.host, checkout: facts.checkout });\n  invocation();",
    check: "tools/checks/architecture/architecture.check.ts",
    fragment: "frameReads equals the baseline",
  },
  {
    id: "C91",
    finding: "O3 empty OC_APP",
    note: "a blank OC_APP is an explicit empty selection, not the unset default",
    product: "tools/framework/entry/resolve.ts",
    search: "  return value.trim() === \"\" ? { state: \"empty\" } : { state: \"named\", name: value };",
    replace: "  return value.trim() === \"\" ? { state: \"unset\" } : { state: \"named\", name: value };",
    check: "tools/checks/surfaces/frame-law.check.ts",
    fragment: "selection EMPTY OC_APP",
  },
  {
    id: "C92",
    finding: "S1.3 rooted invocation hints",
    note: "production-rendered hints from a rooted frame must name the entry relative to that root and cwd",
    product: "tools/framework/core/io/invocation/frame.ts",
    search: "  const path = rel(from, root, platform);",
    replace: "  const path = rel(root, from, platform);",
    check: "tools/checks/integration/apps/invocation-hints-rooted.check.ts",
    fragment: "frame rooted relative hint",
  },
  {
    id: "C93",
    finding: "S1.3 delegated spawn",
    note: "the executed delegated spawn preserves its argv, inherited cwd and selected-app handover",
    product: "tools/framework/entry/delegate.ts",
    search: "    stdio: \"inherit\",\n    env: { ...process.env, [INVOCATION_ENV]: serializeInvocation(handoverOf(frame)), ...(flag ? { [DELEGATED]: \"1\" } : {}) },",
    replace: "    stdio: \"inherit\",\n    cwd: dirname(entry),\n    env: { ...process.env, [INVOCATION_ENV]: serializeInvocation(handoverOf(frame)), ...(flag ? { [DELEGATED]: \"1\" } : {}) },",
    check: "tools/checks/integration/apps/invocation-hints-rooted.check.ts",
    fragment: "delegated spawn inherits cwd",
  },
  {
    id: "C130",
    finding: "S3.2 residual",
    note: "build's refusal selection must use the diagnostic's structural source, not prose — the afterRecipe gate swaps to \"agent-config\", so an agent diagnostic whose text contains \"acceptance.json\" (agentId \"acceptance.json\") wins and the prose-substring bug resurfaces: the expected acceptance refusal is not produced",
    product: "tools/framework/set/load.ts",
    search: "const acceptanceProblem = diagnostics.find((entry) => entry.source === \"acceptance\");",
    replace: "const acceptanceProblem = diagnostics.find((entry) => entry.source === \"agent-config\");",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "refuses with the acceptance error before the agent diagnostic",
  },
  {
    id: "C131",
    finding: "S3.2 residual",
    note: "the portable-content builder's `read` must memoize into `cache` — deleting the memoized entry forces a physical re-read on every access, breaking once-per-path",
    product: "tools/framework/set/content.ts",
    search: "    let pending = cache.get(abs);",
    replace: "    let pending = cache.get(abs);\n    cache.delete(abs);",
    check: "tools/checks/sets/lifecycle/portable-content.check.ts",
    fragment: "physically read once",
  },
  {
    id: "C150",
    finding: "fix33-Y item 1",
    note: "the proseHeld measurement is scope-aware: replacing the lexical lookup with one file-wide set of spaced const names reinstates the scope-insensitive measurement, so the table's shadowing case fails",
    product: "tools/checks/architecture/prose-held.ts",
    search: `  const visible = (name: string, at: number, from: Scope): boolean => { for (let s: Scope | undefined = from; s !== undefined; s = s.parent) { const d = s.held.get(name); if (d !== undefined) return d.spaced && (s !== from || d.at < at); } return false; };`,
    replace: `  const visible = (name: string): boolean => allSpaced.has(name);`,
    check: "tools/checks/architecture/self/prose-held.check.ts",
    fragment: "a shadowing const ends the outer held name",
  },
  {
    id: "C151",
    finding: "fix33-Y item 2",
    note: "the tokenizer's regex-start rule stays punctuation-gated: starting a regex after any non-string token makes division after an identifier tokenize as a regex, failing the table's division case",
    product: "tools/checks/architecture/prose-held.ts",
    search: `previous === undefined || (previous.kind === "p" && ["(", ",", ":", "=", "!", "?", "[", "{", ";", "|", "&"].includes(previous.text))`,
    replace: `previous === undefined || previous.kind === "id" || (previous.kind === "p" && ["(", ",", ":", "=", "!", "?", "[", "{", ";", "|", "&"].includes(previous.text))`,
    check: "tools/checks/architecture/self/prose-held.check.ts",
    fragment: "after identifiers stay division",
  },
  {
    id: "C120",
    finding: "D4/S1.4 checkout-subfolder cd rows",
    note: "the cmd/pwsh alternative must be pushd (drive change in cmd): a bare cd lands cmd in the wrong drive",
    product: "tools/framework/core/io/invocation/advice.ts",
    search: "    alternatives.cmd = alternatives.pwsh = `pushd \"${path}\"`;",
    replace: "    alternatives.cmd = alternatives.pwsh = `cd ${shellQuote(path)}`;",
    check: "tools/checks/surfaces/checkout-subfolder-rows.check.ts",
    fragment: "cmd.exe lands in the target",
  },
  {
    id: "C121",
    finding: "O2/S1.4 --project-root quoting",
    note: "the --project-root path must be quoted by the frame's shells rule — a path with a space must not corrupt the line",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "    parts.push(\"--project-root\", quote(projectRoot));",
    replace: "    parts.push(\"--project-root\", projectRoot);",
    check: "tools/checks/surfaces/advice/advice-anchor.check.ts",
    fragment: "case 4 quotes the --project-root path for cmd/pwsh by the frame's shells rule",
  },
  {
    id: "C122",
    finding: "O2/S1.4 case-4 --project-root selector",
    note: "a known checkout root must turn the cwd-conflict advice into a --project-root row that runs there, not an --app refusal",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "  const projectRoot = cwdConflict && frame.places.checkoutRoot !== undefined\n    ? `${frame.places.checkoutRoot}/apps/${advice.app}`\n    : undefined;",
    replace: "  const projectRoot = false && cwdConflict && frame.places.checkoutRoot !== undefined\n    ? `${frame.places.checkoutRoot}/apps/${advice.app}`\n    : undefined;",
    check: "tools/checks/surfaces/advice/advice-anchor.check.ts",
    fragment: "case 4 carries no --app and no note",
  },
  {
    id: "C123",
    finding: "S1.4 completion install shell",
    note: "shell-named advice rows must render through the shell's own frame — ignoring advice.shell corrupts the pwsh install line",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "  const f = advice.shell === undefined ? frame : forShell(frame, advice.shell);",
    replace: "  const f = advice.shell === undefined ? frame : frame; // control: shell ignored",
    check: "tools/checks/golden/golden.check.ts",
    fragment: "advice-matrix.txt differs from the committed snapshot",
  },
  {
    id: "C124",
    finding: "S1.4 second pass prose frame",
    note: "the prose default must render through the whole installed frame — dropping the installed fallback rebuilds a rootless frame and loses the entry's real roots/places",
    product: "tools/framework/core/io/invocation/index.ts",
    search: "  return installed ?? frameFromInvocation(invocation(), frameFacts());",
    replace: "  return frameFromInvocation(invocation(), frameFacts());",
    check: "tools/checks/surfaces/advice/advice-matrix.check.ts",
    fragment: "prose default names another deployment with --project-root",
  },
  {
    id: "C125",
    finding: "O2/S1.4 case-4 paste cwd",
    note: "the cross-deployment line must run from inside the cwd-selected deployment via --project-root; dropping the selector makes the law fail",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "  const projectRoot = cwdConflict && frame.places.checkoutRoot !== undefined",
    replace: "  const projectRoot = undefined && cwdConflict && frame.places.checkoutRoot !== undefined",
    check: "tools/checks/surfaces/frame-law.check.ts",
    fragment: "system-wide inside apps/demo (cwd selection) | deploy: remote bootstrap command | posix",
  },
  {
    id: "C126",
    finding: "S1.4 help usage frame",
    note: "help usage must render from the caller's whole Frame — projecting it to a hand-over Invocation rebuilds a rootless frame and loses the caller's cwd",
    product: "tools/framework/core/io/help-render.ts",
    search: "    ? { frame: source, on: source }",
    replace: "    ? { frame: source, on: { program: \"clawforge\", mode: \"installed\", audience: \"terminal\" } as Invocation }",
    check: "tools/checks/surfaces/advice/advice-matrix.check.ts",
    fragment: "help usage renders from the installed-style Frame's cwd",
  },
  {
    id: "C127",
    finding: "S1.4 pwsh install sentence",
    note: "under a bash-only fallback the pwsh install guidance must be a sentence naming the condition — a note before the pipe corrupts the command",
    product: "tools/framework/integration/completion/pwsh.ts",
    search: "  const installText = install.note?.includes(\"in bash\") === true\n    ? `run ${install.line} in Git Bash, save the output to a file, and dot-source it from PowerShell`\n    : `${install.line} | Out-String | Invoke-Expression${install.note === undefined ? \"\" : `  (${install.note})`}`;",
    replace: "  const installText = `${install.line}  (${install.note}) | Out-String | Invoke-Expression`;",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "the pwsh Install header's note rides after the whole line",
  },
  {
    id: "C152",
    finding: "rf7-tails-Z item 1",
    note: "function/arrow parameters stay in scope across a return-type annotation: deleting the balanced-type skip makes the scanner treat the annotated body as a plain block (or take the return-type identifier as a parameter), so the table's return-type cases fail",
    product: "tools/checks/architecture/prose-held.ts",
    search: `        // a return-type annotation may sit between ")" and the body ("{" or "=>"): skip it
        let after = pe + 1;
        if (t[after]?.text === ":") { const j = skipType(after + 1); if (j >= 0) after = j; }`,
    replace: `        const after = pe + 1;`,
    check: "tools/checks/architecture/self/prose-held.check.ts",
    fragment: "a function parameter stays in scope with a return-type annotation",
  },
  {
    id: "C153",
    finding: "rf7-tails-Z item 2",
    note: "the transport-read guard accepts a catch only when EVERY path terminates (throw/die or the typed read outcome): restoring the old any-throw-anywhere acceptance re-validates conditional rethrows with a swallowing else path, failing the table case naming it",
    product: "tools/checks/foundation/hygiene/static/transport-read-swallow-rules.ts",
    search: `export function handlerSwallows(handler: string): boolean {
  return !safePaths(handler);
}`,
    replace: `export function handlerSwallows(handler: string): boolean {
  return !new RegExp("\\\\bthrow\\\\b|\\\\bdie\\\\s*\\\\(").test(handler);
}`,
    check: "tools/checks/foundation/hygiene/static/transport-read-swallow.check.ts",
    fragment: "a conditional rethrow with a swallowing else path is a hit",
  },
  {
    id: "C160",
    finding: "S1.5 risk (1)",
    note: "durable text is spelled from the TARGET frame (design risk 1: a reinstall must not report a change): rendering the completion Install header from the ambient operator frame re-stores the subdirectory-relative spelling (../clawforge) into a script that executes elsewhere",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "  return renderAdviceParts(command(argv, { shell }), targetFrame(currentFrame(), shell), undefined, invocation().program)[0]!;",
    replace: "  return renderAdviceParts(command(argv, { shell }), currentFrame(), undefined, invocation().program)[0]!; // control: the operator frame drives the stored line",
    check: "tools/checks/golden/durable-frame.check.ts",
    fragment: "never the operator's cwd",
  },
  {
    id: "C161",
    finding: "R18-06",
    note: "the stored bash Install line must not pick up the operator's own program spelling: dropping the target frame and the shell re-spells it under the operator's shell, so npm's Windows wrapper (backslashes) lands in a bash line",
    product: "tools/framework/core/io/invocation/render.ts",
    search: "  return renderAdviceParts(command(argv, { shell }), targetFrame(currentFrame(), shell), undefined, invocation().program)[0]!;",
    replace: "  return renderAdviceParts(command(argv), currentFrame(), undefined, invocation().program)[0]!; // control: shell ignored, operator frame",
    check: "tools/checks/golden/durable-frame.check.ts",
    fragment: "the operator's Windows wrapper",
  },
  {
    id: "C140",
    finding: "S2.8",
    note: "the lenient mode hands a declared flag to the option again: the pending branch must refuse a declared flag as the pending option's value (option-missing-value)",
    product: "tools/framework/core/command/parse/scan.ts",
    search: "      if (named !== undefined) {\n        return { kind: \"refusal\", reason: \"option-missing-value\", token, argument: waiting };",
    replace: "      if (named !== undefined && named.kind === \"never\") {\n        return { kind: \"refusal\", reason: \"option-missing-value\", token, argument: waiting };",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "the flag binds as a flag",
  },
  {
    id: "C141",
    finding: "S2.8",
    note: "a repeated option must overwrite its earlier entry in place; appending a second entry drifts the lenient record from strict",
    product: "tools/framework/core/command/parse/scan.ts",
    search: "  else entries[at] = { argument: entries[at].argument, value };",
    replace: "  else entries.push({ argument: entries[at].argument, value });",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "a repeated option overwrites its value",
  },
  {
    id: "C142",
    finding: "S2.8",
    note: "an unknown token is a pure skip: the state must not move past the next token, or the lenient scan diverges from strict",
    product: "tools/framework/core/command/parse/scan.ts",
    search: "    if (transition.kind === \"refusal\") {\n      index += 1;\n      continue;\n    }",
    replace: "    if (transition.kind === \"refusal\") {\n      if (transition.reason === \"unknown\") state = { ...state, pending: declared.find((argument) => argument.kind === \"option\")?.name, tail: true };\n      index += 1;\n      continue;\n    }",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "an unknown token does not move the state",
  },
  {
    id: "C143",
    finding: "S2.8",
    note: "the dashed lookups stay restricted to flags and options as HEAD's parser did; widening the lookup binds a positional name as an inline option",
    product: "tools/framework/core/command/parse/scan.ts",
    search: "    const argument = flagToken.startsWith(\"--\") ? slice.arguments.find((candidate) => candidate.name === flagToken.slice(2) && (candidate.kind === \"flag\" || candidate.kind === \"option\")) : undefined;",
    replace: "    const argument = flagToken.startsWith(\"--\") ? slice.arguments.find((candidate) => candidate.name === flagToken.slice(2)) : undefined;",
    check: "tools/checks/foundation/core/command/spec/parse.check.ts",
    fragment: "dashed positional is refused",
  },
  {
    id: "C144",
    finding: "S2.8",
    note: "the oracle reads the registry, not CompletionData; corrupting only the model's declaration copy must break the differential",
    product: "tools/framework/integration/completion/table.ts",
    search: "  const declared = data.declared.get(cmd) ?? [];",
    replace: "  const declared = (data.declared.get(cmd) ?? []).filter((argument) => argument.kind !== \"option\");",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "agrees with the table",
  },
  {
    id: "C145",
    finding: "S2.8",
    note: "a repeated PENDING option must end PENDING: breaking out of the recovery loop instead of recovering skips the repeat and loses the second --client",
    product: "tools/framework/core/command/parse/scan.ts",
    search: "      if (transition.reason === \"option-repeated\") {\n        state = { ...state, seen: state.seen.filter((name) => name !== argument?.name) };\n        transition = step(state, token, slice);\n        continue;\n      }",
    replace: "      if (transition.reason === \"option-repeated\") {\n        break;\n      }",
    check: "tools/checks/foundation/core/command/completion/completion-behaviour.check.ts",
    fragment: "a repeated pending option ends pending",
  },
];
